services:
  postgres:
    image: postgres:16
    container_name: pgsql_db
    environment:
      POSTGRES_USER: ${POST_USER}
      POSTGRES_PASSWORD: ${POST_PASSWORD}
      POSTGRES_DB: ${DBNAME}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "${DOCKER_IP}:${PG_PORT}:5432"
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "config_file=/var/lib/postgresql/data/postgresql.conf"
networks:
  db_network:
    name: db_network
    driver: bridge

volumes:
  postgres_data: